#
# 1. Server Settings
#
server:
  port: 48080
  http2:
    enabled: false
  tomcat:
    response-buffer-size: 1
  compression:
    enabled: false
#  servlet:
#    context-path: /api

#
# 2. Spring Settings
#
spring:
  application:
    name: "${rootProject.name}"
    version: "${project.version}"
  #profile
  profiles:
    active: "${profile}"
#  webflux:
#    hiddenmethod:
#      filter:
#        enabled: false

  #DB
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool

  #JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma:8.5b

#
# 3. Actuator Settings
#
info:
  app:
    name: "${project.name}"
    description: "This is a ${rootProject.name} Spring Boot application."
    version: "${project.version}"
    product: "${project.ext.profile}"
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
        exclude:
      base-path: /healthcheck

#
# 4. Logging Settings
#
logging:
  config: classpath:log4j2.yml
  level:
    root: INFO
    kr.co.iteyes: DEBUG
    org.springframework.security: TRACE


#
# 5. Value Settings
member:
  list:
    default-limit: 3
chat:
  list:
    default-limit: 9999


#
# 6. Profile Settings
#
---
#local
spring:
  config:
    activate:
      on-profile: local

  #DB
  datasource:
    url: jdbc:h2:mem:genaicbtest;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: test
    password: 'test!2'

  h2:
    console:
      enabled: true           # H2 ?? ???
      path: /h2-console       # H2 ?? ?? ?? (???: /h2-console)

  sql:
    init:
      platform: h2

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

mvc:
  cors:
    mappings:
      "/**":
        allowed-origins:
          - http://localhost:3000
          - http://localhost:33000
          - http://192.168.0.42:3000
          - http://192.168.0.42:33000
        allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
---
#dev
spring:
  config:
    activate:
      on-profile: dev

  #DB
  datasource:
    url: jdbc:postgresql://localhost:5432/genai_code_booster
    driver-class-name: org.postgresql.Driver
    username: genaicb
    password: 'genaicb!2'

  sql:
    init:
      platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgresDialect
---
#prod
spring:
  config:
    activate:
      on-profile: prod

  #DB
  datasource:
    url: jdbc:postgresql://localhost:5432/genai_code_booster
    driver-class-name: org.postgresql.Driver
    username: genaicb
    password: 'genaicb!2'

  sql:
    init:
      platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgresDialect

---
#stg
# spring:
#   config:
#     activate:
#       on-profile: stg
#   jpa:
#     show-sql: true
# logging:
#   level:
#     root: INFO
#     kr.co.iteyes: DEBUG
---
